"""empty message

Revision ID: f3e15d04eca8
Revises: 79f1a1a2fe0d
Create Date: 2022-06-06 11:43:07.617069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3e15d04eca8'
down_revision = '79f1a1a2fe0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('created_date', sa.DateTime(), nullable=True))
    op.add_column('venue', sa.Column('created_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE artist SET created_date = %s WHERE artist IS NULL;', (str('2022 -06-04 09:47:S')))
    op.execute('UPDATE venue SET created_date = %s WHERE artist IS NULL;', (str('2022 -06-04 09:47:S')))

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'created_date')
    op.drop_column('artist', 'created_date')
    # ### end Alembic commands ###
